In [1]:
import sys
print(sys.version)

3.10.21 (main, Aug 12 2026, 23:03:10) [Clang 21.0.0 (clang-2100.1.1.101)]

# Phase 1 — Domain & Data Collection

## Project Domain

The domain of this RAG assistant is AI, Machine Learning, and Deep Learning
technical documentation and educational resources.

The assistant will allow users to ask questions about topics related to
Python, Machine Learning, Deep Learning, TensorFlow, scikit-learn, and
PyTorch, and retrieve relevant information from the collected documents.

## Data Sources

The document collection consists of PDF-based technical and educational
resources stored in the `data/documents/` directory.

The documents are organized into folders where necessary to keep the
document collection structured.

# RAG-Powered Document Assistant

## 1. Load & Inspect Documents

In this section, we load the source PDF documents and inspect their
extracted text before preparing them for the RAG pipeline.

In [2]:
from pathlib import Path
from pypdf import PdfReader

In [3]:
#adding the path of the data 

documents_path = Path("//Users/yehiashady/Desktop/rag-assistant-project/data/documents")


print("Documents folder:", documents_path)
print("Folder exists:", documents_path.exists())

Documents folder: //Users/yehiashady/Desktop/rag-assistant-project/data/documents
Folder exists: True

In [4]:
# make sure that all of the data is inserted in the code 

pdf_files = list(documents_path.rglob("*.pdf"))

print("Number of PDF files:", len(pdf_files))

for pdf in pdf_files:
    print("-", pdf.name)

Number of PDF files: 30
- TensorFlow-User-Guide.pdf
- scikit-learn-docs.pdf
- Deep-Learning-with-PyTorch.pdf
- howto-functional.pdf
- howto-pyporting.pdf
- howto-ipaddress.pdf
- distributing.pdf
- installing.pdf
- howto-urllib2.pdf
- library.pdf
- whatsnew.pdf
- howto-logging.pdf
- howto-regex.pdf
- howto-annotations.pdf
- tutorial.pdf
- reference.pdf
- howto-instrumentation.pdf
- extending.pdf
- howto-unicode.pdf
- howto-descriptor.pdf
- howto-cporting.pdf
- howto-argparse.pdf
- howto-clinic.pdf
- using.pdf
- howto-logging-cookbook.pdf
- faq.pdf
- c-api.pdf
- howto-sorting.pdf
- howto-sockets.pdf
- howto-curses.pdf

In [5]:
# open the PDFs and and extarct text to load in the next cell using the function load_pdf

def load_pdf(pdf_path):
    reader = PdfReader(pdf_path)
    
    text = ""
    
    for page in reader.pages: #function to keep opening pages in PDFs
        page_text = page.extract_text()
        
        if page_text:
            text += page_text + "\n"
    
    return text

In [6]:
#reads the content of every PDF

documents = {} # to store the extracted text in the empty dictionary

for pdf in pdf_files:
    text = load_pdf(pdf) 
    documents[str(pdf.relative_to(documents_path))] = text # actual storing 
    
    print(f"✅ {pdf.relative_to(documents_path)}: {len(text):,} characters")

✅ TensorFlow-User-Guide.pdf: 73,247 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 32, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEP+Univers-Light', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 65, '/FontDescriptor': IndirectObject(18573, 0, 4495230240), '/LastChar': 78, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [667, 0, 0, 0, 0, 0, 722, 0, 278, 0, 0, 0, 944, 722]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBFA+Univers', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18575, 0, 4495230240), '/LastChar': 84, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [278, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 722, 0, 0, 722, 611, 0, 0, 722, 278, 0, 0, 556, 0, 778, 0, 0, 0, 667, 667, 611]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBKA+NewBaskerville-BoldItalic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7803, 0, 4495230240), '/LastChar': 146, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 400, 400, 0, 520, 280, 220, 280, 0, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 280, 0, 0, 0, 0, 440, 0, 600, 600, 620, 700, 600, 540, 720, 760, 340, 340, 0, 580, 880, 700, 700, 580, 0, 640, 480, 620, 700, 580, 840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 480, 380, 520, 400, 260, 440, 520, 300, 260, 460, 260, 740, 500, 460, 520, 480, 380, 340, 280, 520, 460, 680, 420, 400, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBKA+NewBaskerville-BoldItalic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7803, 0, 4495230240), '/LastChar': 146, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 400, 400, 0, 520, 280, 220, 280, 0, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 280, 0, 0, 0, 0, 440, 0, 600, 600, 620, 700, 600, 540, 720, 760, 340, 340, 0, 580, 880, 700, 700, 580, 0, 640, 480, 620, 700, 580, 840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 480, 380, 520, 400, 260, 440, 520, 300, 260, 460, 260, 740, 500, 460, 520, 480, 380, 340, 280, 520, 460, 680, 420, 400, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBLB+FranklinGothic-Demi', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7814, 0, 4495230240), '/LastChar': 215, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [300, 320, 0, 0, 0, 0, 0, 0, 380, 380, 0, 0, 300, 240, 300, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 300, 300, 0, 0, 0, 0, 0, 640, 660, 660, 660, 580, 540, 660, 660, 300, 400, 640, 500, 880, 660, 660, 620, 660, 660, 600, 540, 660, 600, 900, 640, 600, 660, 0, 0, 0, 0, 500, 0, 540, 540, 540, 540, 540, 300, 560, 540, 260, 260, 560, 260, 820, 540, 540, 540, 540, 340, 500, 380, 540, 480, 740, 540, 480, 420, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 480, 480, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBKA+NewBaskerville-BoldItalic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7803, 0, 4495230240), '/LastChar': 146, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 400, 400, 0, 520, 280, 220, 280, 0, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 280, 0, 0, 0, 0, 440, 0, 600, 600, 620, 700, 600, 540, 720, 760, 340, 340, 0, 580, 880, 700, 700, 580, 0, 640, 480, 620, 700, 580, 840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 480, 380, 520, 400, 260, 440, 520, 300, 260, 460, 260, 740, 500, 460, 520, 480, 380, 340, 280, 520, 460, 680, 420, 400, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ scikit-learn-docs.pdf: 5,119,909 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBKA+NewBaskerville-BoldItalic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7803, 0, 4495230240), '/LastChar': 146, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 400, 400, 0, 520, 280, 220, 280, 0, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 280, 0, 0, 0, 0, 440, 0, 600, 600, 620, 700, 600, 540, 720, 760, 340, 340, 0, 580, 880, 700, 700, 580, 0, 640, 480, 620, 700, 580, 840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 480, 380, 520, 400, 260, 440, 520, 300, 260, 460, 260, 740, 500, 460, 520, 480, 380, 340, 280, 520, 460, 680, 420, 400, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBLB+FranklinGothic-Demi', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7814, 0, 4495230240), '/LastChar': 215, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [300, 320, 0, 0, 0, 0, 0, 0, 380, 380, 0, 0, 300, 240, 300, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 300, 300, 0, 0, 0, 0, 0, 640, 660, 660, 660, 580, 540, 660, 660, 300, 400, 640, 500, 880, 660, 660, 620, 660, 660, 600, 540, 660, 600, 900, 640, 600, 660, 0, 0, 0, 0, 500, 0, 540, 540, 540, 540, 540, 300, 560, 540, 260, 260, 560, 260, 820, 540, 540, 540, 540, 340, 500, 380, 540, 480, 740, 540, 480, 420, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 480, 480, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBKA+NewBaskerville-BoldItalic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7803, 0, 4495230240), '/LastChar': 146, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 400, 400, 0, 520, 280, 220, 280, 0, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 280, 0, 0, 0, 0, 440, 0, 600, 600, 620, 700, 600, 540, 720, 760, 340, 340, 0, 580, 880, 700, 700, 580, 0, 640, 480, 620, 700, 580, 840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 480, 380, 520, 400, 260, 440, 520, 300, 260, 460, 260, 740, 500, 460, 520, 480, 380, 340, 280, 520, 460, 680, 420, 400, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBLB+FranklinGothic-Demi', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7814, 0, 4495230240), '/LastChar': 215, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [300, 320, 0, 0, 0, 0, 0, 0, 380, 380, 0, 0, 300, 240, 300, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 300, 300, 0, 0, 0, 0, 0, 640, 660, 660, 660, 580, 540, 660, 660, 300, 400, 640, 500, 880, 660, 660, 620, 660, 660, 600, 540, 660, 600, 900, 640, 600, 660, 0, 0, 0, 0, 500, 0, 540, 540, 540, 540, 540, 300, 560, 540, 260, 260, 560, 260, 820, 540, 540, 540, 540, 340, 500, 380, 540, 480, 740, 540, 480, 420, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 480, 480, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBKA+NewBaskerville-BoldItalic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7803, 0, 4495230240), '/LastChar': 146, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 400, 400, 0, 520, 280, 220, 280, 0, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 280, 0, 0, 0, 0, 440, 0, 600, 600, 620, 700, 600, 540, 720, 760, 340, 340, 0, 580, 880, 700, 700, 580, 0, 640, 480, 620, 700, 580, 840, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 480, 380, 520, 400, 260, 440, 520, 300, 260, 460, 260, 740, 500, 460, 520, 480, 380, 340, 280, 520, 460, 680, 420, 400, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 260]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBLB+FranklinGothic-Demi', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7814, 0, 4495230240), '/LastChar': 215, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [300, 320, 0, 0, 0, 0, 0, 0, 380, 380, 0, 0, 300, 240, 300, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 600, 300, 300, 0, 0, 0, 0, 0, 640, 660, 660, 660, 580, 540, 660, 660, 300, 400, 640, 500, 880, 660, 660, 620, 660, 660, 600, 540, 660, 600, 900, 640, 600, 660, 0, 0, 0, 0, 500, 0, 540, 540, 540, 540, 540, 300, 560, 540, 260, 260, 560, 260, 820, 540, 540, 540, 540, 340, 500, 380, 540, 480, 740, 540, 480, 420, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 480, 480, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 300, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 600]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBEO+NewBaskerville-Roman', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18565, 0, 4495230240), '/LastChar': 248, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 320, 0, 520, 0, 900, 0, 220, 440, 440, 500, 520, 260, 240, 260, 580, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 260, 260, 0, 520, 520, 400, 820, 660, 640, 680, 740, 620, 540, 740, 820, 360, 340, 660, 620, 880, 760, 820, 580, 800, 660, 520, 660, 780, 640, 900, 740, 520, 600, 440, 0, 440, 0, 500, 360, 480, 560, 460, 580, 500, 320, 520, 600, 280, 260, 520, 280, 860, 600, 560, 580, 560, 400, 360, 320, 580, 420, 640, 520, 420, 420, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 300, 400, 400, 0, 500, 1000, 0, 0, 0, 0, 0, 0, 0, 0, 260, 0, 0, 0, 0, 0, 0, 0, 380, 740, 0, 0, 0, 240, 0, 0, 400, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 520, 0, 0, 0, 0, 0, 0, 0, 0, 0, 480, 0, 0, 480, 0, 0, 0, 0, 500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 560]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBJP+NewBaskerville-Bold', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(7806, 0, 4495230240), '/LastChar': 120, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 0, 0, 0, 0, 0, 0, 640, 0, 700, 740, 620, 560, 780, 820, 380, 0, 0, 620, 880, 780, 840, 620, 0, 700, 540, 680, 780, 0, 880, 0, 620, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 460, 0, 540]}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/BaseFont': '/BDFBDN+NewBaskerville-Italic', '/Encoding': '/WinAnsiEncoding', '/FirstChar': 32, '/FontDescriptor': IndirectObject(18566, 0, 4495230240), '/LastChar': 151, '/Subtype': '/Type1', '/Type': '/Font', '/Widths': [260, 300, 0, 0, 0, 0, 0, 0, 340, 340, 0, 520, 280, 240, 280, 440, 520, 520, 520, 520, 520, 520, 520, 520, 520, 520, 280, 280, 0, 0, 0, 440, 0, 640, 600, 620, 660, 560, 480, 680, 780, 340, 300, 660, 600, 880, 700, 700, 560, 0, 640, 480, 640, 680, 580, 840, 640, 580, 560, 0, 0, 0, 0, 500, 0, 500, 420, 360, 500, 340, 280, 440, 500, 280, 260, 440, 260, 720, 560, 420, 480, 440, 340, 340, 280, 560, 480, 640, 460, 380, 360, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 420, 420, 0, 0, 1000]}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ Deep-Learning-with-PyTorch.pdf: 1,094,253 characters
✅ docs-pdf/howto-functional.pdf: 45,814 characters
✅ docs-pdf/howto-pyporting.pdf: 21,300 characters
✅ docs-pdf/howto-ipaddress.pdf: 11,480 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1027, 0, 4683469520), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/UJJKGS+CMMI5', '/FontDescriptor': IndirectObject(1065, 0, 4683469520)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1027, 0, 4683469520), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/UJJKGS+CMMI5', '/FontDescriptor': IndirectObject(1065, 0, 4683469520)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/distributing.pdf: 107,771 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1027, 0, 4695116096), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYJOEI+CMMI5', '/FontDescriptor': IndirectObject(1065, 0, 4695116096)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1027, 0, 4695116096), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYJOEI+CMMI5', '/FontDescriptor': IndirectObject(1065, 0, 4695116096)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/installing.pdf: 109,956 characters
✅ docs-pdf/howto-urllib2.pdf: 22,881 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(65612, 0, 4691797104), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/WPWWOD+CMMI5', '/FontDescriptor': IndirectObject(65665, 0, 4691797104)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/library.pdf: 5,375,345 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(968, 0, 4685534240), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NFRUAU+CMMI5', '/FontDescriptor': IndirectObject(1008, 0, 4685534240)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(968, 0, 4685534240), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NFRUAU+CMMI5', '/FontDescriptor': IndirectObject(1008, 0, 4685534240)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(968, 0, 4685534240), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NFRUAU+CMMI5', '/FontDescriptor': IndirectObject(1008, 0, 4685534240)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(239, 0, 4747350016), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/SAOARO+CMMI5', '/FontDescriptor': IndirectObject(278, 0, 4747350016)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/whatsnew.pdf: 83,076 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(239, 0, 4747350016), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/SAOARO+CMMI5', '/FontDescriptor': IndirectObject(278, 0, 4747350016)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/howto-logging.pdf: 39,974 characters
✅ docs-pdf/howto-regex.pdf: 50,248 characters
✅ docs-pdf/howto-annotations.pdf: 8,840 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2034, 0, 4680034736), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NBPUFU+CMMI5', '/FontDescriptor': IndirectObject(2073, 0, 4680034736)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2034, 0, 4680034736), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NBPUFU+CMMI5', '/FontDescriptor': IndirectObject(2073, 0, 4680034736)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2034, 0, 4680034736), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NBPUFU+CMMI5', '/FontDescriptor': IndirectObject(2073, 0, 4680034736)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2034, 0, 4680034736), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NBPUFU+CMMI5', '/FontDescriptor': IndirectObject(2073, 0, 4680034736)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/tutorial.pdf: 320,727 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(5144, 0, 4680040400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/MZUXFV+CMMI5', '/FontDescriptor': IndirectObject(5185, 0, 4680040400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(87, 0, 4691796912), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/EZTKAR+CMMI5', '/FontDescriptor': IndirectObject(117, 0, 4691796912)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(87, 0, 4691796912), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/EZTKAR+CMMI5', '/FontDescriptor': IndirectObject(117, 0, 4691796912)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/reference.pdf: 460,466 characters
✅ docs-pdf/howto-instrumentation.pdf: 12,796 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1506, 0, 4690074720), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYCVDR+CMMI5', '/FontDescriptor': IndirectObject(1545, 0, 4690074720)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1506, 0, 4690074720), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYCVDR+CMMI5', '/FontDescriptor': IndirectObject(1545, 0, 4690074720)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1506, 0, 4690074720), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYCVDR+CMMI5', '/FontDescriptor': IndirectObject(1545, 0, 4690074720)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1506, 0, 4690074720), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYCVDR+CMMI5', '/FontDescriptor': IndirectObject(1545, 0, 4690074720)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(1506, 0, 4690074720), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/NYCVDR+CMMI5', '/FontDescriptor': IndirectObject(1545, 0, 4690074720)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/extending.pdf: 256,807 characters
✅ docs-pdf/howto-unicode.pdf: 27,808 characters
✅ docs-pdf/howto-descriptor.pdf: 38,395 characters
✅ docs-pdf/howto-cporting.pdf: 778 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(285, 0, 4683466400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/PUKOFS+CMMI5', '/FontDescriptor': IndirectObject(329, 0, 4683466400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(285, 0, 4683466400), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/PUKOFS+CMMI5', '/FontDescriptor': IndirectObject(329, 0, 4683466400)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/howto-argparse.pdf: 20,096 characters
✅ docs-pdf/howto-clinic.pdf: 58,554 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2214, 0, 4695118784), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/FIBMST+CMMI5', '/FontDescriptor': IndirectObject(2253, 0, 4695118784)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2214, 0, 4695118784), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/FIBMST+CMMI5', '/FontDescriptor': IndirectObject(2253, 0, 4695118784)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2214, 0, 4695118784), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/FIBMST+CMMI5', '/FontDescriptor': IndirectObject(2253, 0, 4695118784)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2214, 0, 4695118784), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/FIBMST+CMMI5', '/FontDescriptor': IndirectObject(2253, 0, 4695118784)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2214, 0, 4695118784), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/FIBMST+CMMI5', '/FontDescriptor': IndirectObject(2253, 0, 4695118784)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/using.pdf: 210,179 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(528, 0, 4695126704), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IAXGFO+CMMI5', '/FontDescriptor': IndirectObject(567, 0, 4695126704)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/howto-logging-cookbook.pdf: 127,163 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2173, 0, 4683017200), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/DZBCBA+CMMI5', '/FontDescriptor': IndirectObject(2212, 0, 4683017200)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2173, 0, 4683017200), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/DZBCBA+CMMI5', '/FontDescriptor': IndirectObject(2212, 0, 4683017200)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2173, 0, 4683017200), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/DZBCBA+CMMI5', '/FontDescriptor': IndirectObject(2212, 0, 4683017200)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(2173, 0, 4683017200), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/DZBCBA+CMMI5', '/FontDescriptor': IndirectObject(2212, 0, 4683017200)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/faq.pdf: 269,684 characters

fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(13231, 0, 4680303568), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IHRTWF+CMMI5', '/FontDescriptor': IndirectObject(13281, 0, 4680303568)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(13231, 0, 4680303568), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IHRTWF+CMMI5', '/FontDescriptor': IndirectObject(13281, 0, 4680303568)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(13231, 0, 4680303568), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IHRTWF+CMMI5', '/FontDescriptor': IndirectObject(13281, 0, 4680303568)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(13231, 0, 4680303568), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/IHRTWF+CMMI5', '/FontDescriptor': IndirectObject(13281, 0, 4680303568)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(99, 0, 4683013792), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/ZYGVCD+CMMI5', '/FontDescriptor': IndirectObject(137, 0, 4683013792)}, but is not installed. Consider installing fontTools if you encounter encoding problems.
fontTools is required to fully parse the encoding of a CFF Type1 font in font dictionary {'/Type': '/Font', '/Subtype': '/Type1', '/Widths': IndirectObject(99, 0, 4683013792), '/FirstChar': 44, '/LastChar': 44, '/BaseFont': '/ZYGVCD+CMMI5', '/FontDescriptor': IndirectObject(137, 0, 4683013792)}, but is not installed. Consider installing fontTools if you encounter encoding problems.

✅ docs-pdf/c-api.pdf: 795,681 characters
✅ docs-pdf/howto-sorting.pdf: 10,701 characters
✅ docs-pdf/howto-sockets.pdf: 18,198 characters
✅ docs-pdf/howto-curses.pdf: 21,790 characters

In [7]:
#making sire that all the text in the pdfs are extarcted 

for filename, text in documents.items(): # gives ther file name and the text
    if len(text.strip()) > 100:
        print(f"✅ {filename} - Text extraction successful")
    else:
        print(f"⚠️ {filename} - Very little text extracted; OCR may be needed")

✅ TensorFlow-User-Guide.pdf - Text extraction successful
✅ scikit-learn-docs.pdf - Text extraction successful
✅ Deep-Learning-with-PyTorch.pdf - Text extraction successful
✅ docs-pdf/howto-functional.pdf - Text extraction successful
✅ docs-pdf/howto-pyporting.pdf - Text extraction successful
✅ docs-pdf/howto-ipaddress.pdf - Text extraction successful
✅ docs-pdf/distributing.pdf - Text extraction successful
✅ docs-pdf/installing.pdf - Text extraction successful
✅ docs-pdf/howto-urllib2.pdf - Text extraction successful
✅ docs-pdf/library.pdf - Text extraction successful
✅ docs-pdf/whatsnew.pdf - Text extraction successful
✅ docs-pdf/howto-logging.pdf - Text extraction successful
✅ docs-pdf/howto-regex.pdf - Text extraction successful
✅ docs-pdf/howto-annotations.pdf - Text extraction successful
✅ docs-pdf/tutorial.pdf - Text extraction successful
✅ docs-pdf/reference.pdf - Text extraction successful
✅ docs-pdf/howto-instrumentation.pdf - Text extraction successful
✅ docs-pdf/extending.pdf - Text extraction successful
✅ docs-pdf/howto-unicode.pdf - Text extraction successful
✅ docs-pdf/howto-descriptor.pdf - Text extraction successful
✅ docs-pdf/howto-cporting.pdf - Text extraction successful
✅ docs-pdf/howto-argparse.pdf - Text extraction successful
✅ docs-pdf/howto-clinic.pdf - Text extraction successful
✅ docs-pdf/using.pdf - Text extraction successful
✅ docs-pdf/howto-logging-cookbook.pdf - Text extraction successful
✅ docs-pdf/faq.pdf - Text extraction successful
✅ docs-pdf/c-api.pdf - Text extraction successful
✅ docs-pdf/howto-sorting.pdf - Text extraction successful
✅ docs-pdf/howto-sockets.pdf - Text extraction successful
✅ docs-pdf/howto-curses.pdf - Text extraction successful

## 2.2 Chunking Strategy

We split the extracted documents into fixed-size chunks of approximately
1000 characters with an overlap of 200 characters.

We use fixed-size chunking with 1000 characters per chunk and 200 characters of overlap, which helps preserve context across chunk boundaries while keeping the retrieved information focused.

An overlap of 200 means that we will retake the last 2 character from the last chunck

Overlapping is important because sometimes the boundries are important

In [8]:
#creating the chunck with a fixed chunk size and overlap 

def create_chunks(text, chunk_size=1000, overlap=200):
    chunks = []

    start = 0

    while start < len(text):
        end = start + chunk_size

        chunk = text[start:end]

        if chunk.strip():
            chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

In [9]:
chunks = [] #contains all the chunks of the pdfs

for filename, text in documents.items(): #Go through every PDF and get its filename and extracted text.

    document_chunks = create_chunks( # chunk of one document uding function create_chunk in the cell before that one 
        text,
        chunk_size=1000,
        overlap=200
    )

    for i, chunk in enumerate(document_chunks): #gets the index and the content of the chunk

        chunks.append({
            "text": chunk,
            "source": filename,
            "chunk_id": i
        })

print("Total chunks:", len(chunks))

Total chunks: 18530

## 2.3 Embeddings

Each document chunk is converted into a numerical vector called an embedding.
We use the `all-MiniLM-L6-v2` model from Sentence Transformers which switch text to a numeric vectors to make searching easier for the RAG

In [14]:
#importing pretrained models for embedding 

from sentence_transformers import SentenceTransformer # needed to get pretrained models used for embedding

embedding_model = SentenceTransformer("all-MiniLM-L6-v2") # loaded th embedding model into a variable

test_embedding = embedding_model.encode("What is overfitting?") # convert question to embedding 

print("Embedding dimensions of each chunk:", len(test_embedding))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Embedding dimensions: 384

In [15]:
#takes all the texts and convert them into embeddings 

texts = [chunk["text"] for chunk in chunks] # get the text of every chunk, related to cell 9

embeddings = embedding_model.encode(
    texts,
    show_progress_bar=True
)

print("Number of chunks:", len(texts))
print("Number of embeddings:", len(embeddings))
print("Embedding dimensions:", len(embeddings[0]))

Batches:   0%|          | 0/580 [00:00<?, ?it/s]

Number of chunks: 18530
Number of embeddings: 18530
Embedding dimensions: 384

## 2.4 Vector Store — ChromaDB

The generated embeddings will be stored in ChromaDB together with the original
text chunks and their source information.

Embedding → to find 
Text → to answer 
Source → where from

In [16]:
import chromadb # search the embedding for the similar chunk, chromadb stores text,embeddings, and source

vector_store_path = "../data/vector_store" # Save my ChromaDB data in the data/vector_store folder.

client = chromadb.PersistentClient( # create the connection to chromadb
    path=vector_store_path
)

print("ChromaDB client created successfully.")

ChromaDB client created successfully.

In [17]:
collection = client.get_or_create_collection( # create a folder inside chromadb called "rag_documents"
    name="rag_documents"
)

print("Collection created successfully.")

Collection created successfully.

In [19]:


client.delete_collection("rag_documents") # to make sure if er run the notebook again we do not create a new collection 

collection = client.get_or_create_collection(
    name="rag_documents"
)
# create id for every chunk, so chromadb knows which piece of info is which 
ids = [
    f"{chunk['source']}_{chunk['chunk_id']}"
    for chunk in chunks
]
# stores the info of every chunk, helps to tell where did the chunk come from
metadatas = [
    {
        "source": chunk["source"],
        "chunk_id": chunk["chunk_id"]
    }
    for chunk in chunks
]

# ChromaDB has a maximum batch size, so we add the data in smaller batches.
batch_size = 5000 # number of chunks per batch as chromadb can not get all chunks at once 

for start in range(0, len(chunks), batch_size):
    end = start + batch_size
# sets the collection with info it needs
    collection.add(
        ids=ids[start:end],
        documents=texts[start:end],
        embeddings=embeddings[start:end].tolist() #converts the embeddings into a regular format that ChromaDB accepts,
        metadatas=metadatas[start:end]
    )

    print(f"Stored {min(end, len(chunks))} / {len(chunks)} chunks")

print("Stored chunks:", collection.count())

Stored 5000 / 18530 chunks
Stored 10000 / 18530 chunks
Stored 15000 / 18530 chunks
Stored 18530 / 18530 chunks
Stored chunks: 18530

In [20]:
def retrieve_documents(question, n_results=5):
 # first did the embedding then converted to a formate to be understood by chromadb  
    question_embedding = embedding_model.encode(question).tolist() 
# search the chromadb with the most relevant info in only 5 chunks
    results = collection.query(
        query_embeddings=[question_embedding],
        n_results=n_results
    )

    return results

In [21]:
#testing cell
question = "What is overfitting?"

results = retrieve_documents(question, n_results=5)

for i, document in enumerate(results["documents"][0]):
    print(f"\n--- Result {i + 1} ---")
    print("Source:", results["metadatas"][0][i]["source"])
    print("Chunk ID:", results["metadatas"][0][i]["chunk_id"])
    print(document[:800])

--- Result 1 ---
Source: Deep-Learning-with-PyTorch.pdf
Chunk ID: 939
pos
Figure 12.18 Our positive loss showing clear signs of overfitting, as the training loss and
validation loss are trending in different directions
345Revisiting the problem of overfitting
12.5 Revisiting the problem of overfitting
We touched on the concept of overfitting in  chapter 5, and now it’s time to take a
closer look at how to address this common situation. Our goal with training a model is
to teach it to recognize the general properties  of the classes we are interested in, as
expressed in our dataset. Those general prop erties are present in some or all samples
of the class and can be generalized and used to predict samples that haven’t been
trained on. When the model starts to learn specific properties of the training set, overfit-
ting occurs, and the model starts to lose th

--- Result 2 ---
Source: Deep-Learning-with-PyTorch.pdf
Chunk ID: 387
3, just because it pushes
the loss very close to zero. Since the beha vior of the function away from the data
points does not increase the loss, there’ s nothing to keep the model in check for
inputs away from the training data points.
Figure 5.13 Rather
extreme example of
overfitting
134 CHAPTER 5 The mechanics of learning
What’s the cure, though? Good question. Fr om what we just said, overfitting really
looks like a problem of making sure the behavior of the model in between data points
is sensible for the process we’re trying to approximate. First of all, we should make
sure we get enough data for the process. If  we collected data from a sinusoidal pro-
cess by sampling it re gularly at a low frequency, we would have a hard time fitting a
model to it.
 A s s u m i n g  w e  h a v e

--- Result 3 ---
Source: Deep-Learning-with-PyTorch.pdf
Chunk ID: 936
ization of network weig hts and random selection and ordering
of training samples per epoch.
The training set numbers don’t seem to be having the same problem. Negative train-
ing samples are classified correctly 98.8% of  the time, and positive samples are 99.1%
correct. What’s going on?
12.4.3 Recognizing the sy mptoms of overfitting
What we are seeing are clear signs of overfitt ing. Let’s take a look at the graph of our
loss on positive samples, in figure 12.18.
344 CHAPTER 12 Improving training with metrics and augmentation
Here, we can see that the training loss for our positive samples is nearly zero—each
positive training sample gets a nearly perf ect prediction. Our vali dation loss for posi-
tive samples is increasing, though, and that means our re al-world performance is likely


--- Result 4 ---
Source: Deep-Learning-with-PyTorch.pdf
Chunk ID: 942

when predicting the ages of any group larger than a small village.
 Our face-to-age model has the capacity to  simply memorize the photos of anyone
who doesn’t look exactly their age. As we discussed in part 1, model capacity is a some-
what abstract concept, but is  roughly a function of the number of parameters of the
model times how efficiently those parame ters are used. When a model has a high
capacity relative to the amount of data needed to memorize the hard samples from
the training set, it’s likely that the model will begin to overfit on those more difficult
training samples.
12.6 Preventing overfitting with data augmentation
It’s time to take our model training from good to great. We need to cover one last step
in figure 12.20.
We augment a dataset by applying synthetic alterat

--- Result 5 ---
Source: Deep-Learning-with-PyTorch.pdf
Chunk ID: 394
ss and the validation loss decreasing. While ideally both losses would be
roughly the same value, as long as the va lidation loss stays reas onably close to the
training loss, we know that our model is continuing to learn generalized things about
our data. In figure 5.14, case C is ideal, while D is acceptable. In case A, the model
isn’t learning at all; and in case B, we see overfitting. We’ll see more meaningful exam-
ples of overfitting in chapter 12.
AB
C
loSs
loSs loSs
loSs
iterations iterations
iterationsiterations
D
Figure 5.14 Overfitting scenarios when looking at the training (solid line) and validation (dotted line)
losses. (A) Training and validation losses do not decrease; the model is not learning due to no
information in the data or insufficient capacity of the model. (B)

In [22]:
#builds the instructions we will send to the LLM.

def build_prompt(question, results):
    context_parts = [] # empty list were the relevent chunks to a certain question will be stored

# goes through the 5 chunks retrieved by ChromaDB, one at a time.
    for i, document in enumerate(results["documents"][0]):
        source = results["metadatas"][0][i]["source"]

        context_parts.append(
            f"[Source {i + 1}: {source}]\n{document}"
        )

    context = "\n\n".join(context_parts) # combine chunks
# instructions sent to the LLM
    prompt = f"""
You are a helpful AI and Machine Learning document assistant.

Answer the user's question using ONLY the information provided in the context.

Rules:
- Do not use outside knowledge.
- Do not invent facts.
- If the answer is not available in the context, say:
  "The information was not found in the provided documents."
- At the end, mention the source document(s) used.

Context:
{context}

Question:
{question}

Answer:
"""

    return prompt

In [23]:
# testing cell
question = "What is overfitting?"

results = retrieve_documents(question, n_results=5)

prompt = build_prompt(question, results)

print(prompt[:5000])

You are a helpful AI and Machine Learning document assistant.

Answer the user's question using ONLY the information provided in the context.

Rules:
- Do not use outside knowledge.
- Do not invent facts.
- If the answer is not available in the context, say:
  "The information was not found in the provided documents."
- At the end, mention the source document(s) used.

Context:
[Source 1: Deep-Learning-with-PyTorch.pdf]
pos
Figure 12.18 Our positive loss showing clear signs of overfitting, as the training loss and
validation loss are trending in different directions
345Revisiting the problem of overfitting
12.5 Revisiting the problem of overfitting
We touched on the concept of overfitting in  chapter 5, and now it’s time to take a
closer look at how to address this common situation. Our goal with training a model is
to teach it to recognize the general properties  of the classes we are interested in, as
expressed in our dataset. Those general prop erties are present in some or all samples
of the class and can be generalized and used to predict samples that haven’t been
trained on. When the model starts to learn specific properties of the training set, overfit-
ting occurs, and the model starts to lose the ability to generalize. In case that’s a bit
too abstract, let’s use another analogy.
12.5.1 An overfit face-to-age prediction model
Let’s pretend we have a model that takes an image of a human face

[Source 2: Deep-Learning-with-PyTorch.pdf]
3, just because it pushes
the loss very close to zero. Since the beha vior of the function away from the data
points does not increase the loss, there’ s nothing to keep the model in check for
inputs away from the training data points.
Figure 5.13 Rather
extreme example of
overfitting
134 CHAPTER 5 The mechanics of learning
What’s the cure, though? Good question. Fr om what we just said, overfitting really
looks like a problem of making sure the behavior of the model in between data points
is sensible for the process we’re trying to approximate. First of all, we should make
sure we get enough data for the process. If  we collected data from a sinusoidal pro-
cess by sampling it re gularly at a low frequency, we would have a hard time fitting a
model to it.
 A s s u m i n g  w e  h a v e  e n o u g h  d a t a  p o i n t s ,  we should make sure the model that is
capable of fitting the training data is as regular as possible in between them. There are
several ways to achieve this. One

[Source 3: Deep-Learning-with-PyTorch.pdf]
ization of network weig hts and random selection and ordering
of training samples per epoch.
The training set numbers don’t seem to be having the same problem. Negative train-
ing samples are classified correctly 98.8% of  the time, and positive samples are 99.1%
correct. What’s going on?
12.4.3 Recognizing the sy mptoms of overfitting
What we are seeing are clear signs of overfitt ing. Let’s take a look at the graph of our
loss on positive samples, in figure 12.18.
344 CHAPTER 12 Improving training with metrics and augmentation
Here, we can see that the training loss for our positive samples is nearly zero—each
positive training sample gets a nearly perf ect prediction. Our vali dation loss for posi-
tive samples is increasing, though, and that means our re al-world performance is likely
getting worse. At this point, it’s often best to stop the training script, since the model
is no longer improving.
TIP Generally, if your model’s performance is improving on your training set
while ge

[Source 4: Deep-Learning-with-PyTorch.pdf]

when predicting the ages of any group larger than a small village.
 Our face-to-age model has the capacity to  simply memorize the photos of anyone
who doesn’t look exactly their age. As we discussed in part 1, model capacity is a some-
what abstract concept, but is  roughly a function of the number of parameters of the
model times how efficiently those parame ters are used. When a model has a high
capacity relative to the amount of data needed to memorize the hard samples from
the training set, it’s likely that the model will begin to overfit on those more difficult
training samples.
12.6 Preventing overfitting with data augmentation
It’s time to take our model training from good to great. We need to cover one last step
in figure 12.20.
We augment a dataset by applying synthetic alterations to individual samples, resulting
in a new dataset with an effective size that is larger than the original. The typical goal
is for the alterations to result in a syntheti c sample that remains re

[Source 5: Deep-Learning-with-PyTorch.pdf]
ss and the validation loss decreasing. While ideally both losses would be
roughly the same value, as long as the va lidation loss stays reas onably close to the
training loss, we know that our model is continuing to learn generalized things about
our data. In figure 5.14, case C is ideal, while D is acceptable. In case A, the model
isn’t learning at all; and in case B, we see overfitting. We’

Setting the LLM

In [25]:
import ollama # tools that help you run the LLM on your computer 

ollama_model = "llama3.2"

print("Ollama model:", ollama_model)

Ollama model: llama3.2

In [26]:
response = ollama.chat(
    model="llama3.2", # the actual LLM
    messages=[
        {
            "role": "user", # message is coming from the user 
            "content": "What is overfitting?" # the question we are receiving 
        }
    ]
)

print(response["message"]["content"])

Overfitting is a common problem in machine learning and artificial intelligence where a model becomes too complex and starts to fit the training data too closely, rather than generalizing well to new, unseen data. In other words, a model that has been trained on a small dataset may perform exceptionally well on that dataset, but it will not perform well on new, different data.

When a model is overfitting, it means that it is learning the noise and patterns in the training data, rather than the underlying relationships and patterns that it should be learning. This can result in poor performance on new data, as the model is not generalizing well to new situations.

There are several reasons why overfitting occurs, including:

1. **Model complexity**: Models that are too complex can lead to overfitting, as they have too many parameters and can fit the noise in the training data.
2. **Small training dataset**: If the training dataset is too small, the model may not have enough information to generalize well to new data.
3. **High dimensionality**: If the feature space is too high-dimensional, the model may have trouble selecting the most important features and may end up overfitting.
4. **Over-regularization**: Regularization techniques can help prevent overfitting, but if over-regularized, they can also prevent the model from fitting the training data well enough.

Some common signs of overfitting include:

1. **High training error**: The model performs well on the training data, but poorly on new data.
2. **Low test error**: The model performs well on the test data, but poorly on new data.
3. **High bias**: The model is too simple and fails to capture the underlying relationships in the data.
4. **Poor generalization**: The model performs poorly on new data, even with high levels of accuracy on the training data.

To prevent overfitting, techniques such as:

1. **Regularization**: Adding a penalty term to the loss function to discourage large weights.
2. **Data augmentation**: Increasing the size of the training dataset by adding noise or other variations.
3. **Cross-validation**: Splitting the data into multiple folds and evaluating the model on each fold to prevent overfitting to a single fold.
4. **Early stopping**: Stopping the training process when the model's performance on the validation set starts to degrade.
5. **Ensemble methods**: Combining the predictions of multiple models to reduce overfitting.

In [27]:
# The Main RAG function

def generate_answer(question, n_results=5):
    # Retrieve relevant documents
    results = retrieve_documents(
        question,
        n_results=n_results
    )

    # Build grounded prompt
    prompt = build_prompt(
        question,
        results
    )

    # Ask the local LLM
    response = ollama.chat(
        model=ollama_model,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ]
    )
# Getting the actual answer
    answer = response["message"]["content"]

    return answer, results

In [28]:
# testing cell
question = "What is overfitting?"

answer, results = generate_answer(
    question,
    n_results=5
)

print("Question:")
print(question)

print("\nAnswer:")
print(answer)

print("\nRetrieved Sources:")

for metadata in results["metadatas"][0]:
    print("-", metadata["source"])

Question:
What is overfitting?

Answer:
Overfitting is a situation where a model starts to learn specific properties of the training set, rather than general properties, and loses its ability to generalize to new, unseen data.

Source documents: Deep-Learning-with-PyTorch.pdf (sections 12.5, 12.5.1, 12.6, 12.4.3, and 12.6)

Retrieved Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf

In [29]:
evaluation_questions = [
    "What is overfitting?",
    "What is underfitting?",
    "What is a neural network?",
    "What is a tensor?",
    "What is gradient descent?",
    "What is cross-validation?",
    "What is a decision tree?",
    "What is a convolutional neural network?",
    "What is an embedding?",
    "What is regularization?"
]

print("Number of evaluation questions:", len(evaluation_questions))

Number of evaluation questions: 10

In [30]:
evaluation_results = []

for i, question in enumerate(evaluation_questions, start=1):

    print(f"Processing question {i}/10...")

    answer, results = generate_answer(
        question,
        n_results=5
    )

    sources = [
        metadata["source"]
        for metadata in results["metadatas"][0]
    ]

    evaluation_results.append({
        "question": question,
        "sources": sources,
        "answer": answer,
        "correct": "",
        "grounded": ""
    })

print("\nEvaluation completed.")

Processing question 1/10...
Processing question 2/10...
Processing question 3/10...
Processing question 4/10...
Processing question 5/10...
Processing question 6/10...
Processing question 7/10...
Processing question 8/10...
Processing question 9/10...
Processing question 10/10...

Evaluation completed.

In [31]:
for i, result in enumerate(evaluation_results, start=1):

    print("\n" + "=" * 80)
    print(f"QUESTION {i}")
    print("=" * 80)

    print("Question:")
    print(result["question"])

    print("\nAnswer:")
    print(result["answer"])

    print("\nSources:")
    for source in result["sources"]:
        print("-", source)

================================================================================
QUESTION 1
================================================================================
Question:
What is overfitting?

Answer:
Overfitting is a situation where a model starts to learn specific properties of the training set, rather than the general properties of the classes, and loses its ability to generalize to new, unseen data.

Source documents used:
- Deep-Learning-with-PyTorch.pdf (Figures 12.18, 12.20, 5.13, 5.14)

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 2
================================================================================
Question:
What is underfitting?

Answer:
The information was not found in the provided documents.

Source document(s) used: Deep-Learning-with-PyTorch.pdf (all documents)

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 3
================================================================================
Question:
What is a neural network?

Answer:
According to the provided documents, a neural network is "mathematical entities capable of representing complicated functions through a composition of simpler functions."

Source document(s) used: Source 3: Deep-Learning-with-PyTorch.pdf and Source 4: Deep-Learning-with-PyTorch.pdf.

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 4
================================================================================
Question:
What is a tensor?

Answer:
According to the provided context, a tensor refers to the generalization of vectors and matrices to an arbitrary number of dimensions, as described in figure 3.2 of the document. It is also referred to as a multidimensional array. The dimensionality of a tensor coincides with the number of indexes used to refer to scalar values within the tensor.

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 5
================================================================================
Question:
What is gradient descent?

Answer:
Gradient descent is an optimization algorithm that minimizes the loss function by repeatedly updating the weights of a model. It computes the gradient of the loss with respect to the weights, and then updates the weights in the direction of the negative gradient. The update rule is given by:

W_i+1 = W_i - α ∇Loss

where W is the weight matrix, i is the iteration step, α is the learning rate, and ∇Loss is the gradient of the loss with respect to the weights.

The information was found in the provided documents, specifically in the section on "Gradient Descent" and "Stochastic Gradient Descent" in scikit-learn-docs.pdf and Deep-Learning-with-PyTorch.pdf.

Sources:
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- Deep-Learning-with-PyTorch.pdf
- scikit-learn-docs.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 6
================================================================================
Question:
What is cross-validation?

Answer:
Cross-validation is a procedure used in machine learning and statistics to evaluate the performance of a model by training and testing it on multiple subsets of the data. This is done to estimate the generalization error of the model and to prevent overfitting.

Source document(s) used: scikit-learn-docs.pdf

Sources:
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf

================================================================================
QUESTION 7
================================================================================
Question:
What is a decision tree?

Answer:
A decision tree is a non-parametric supervised learning method used for classiﬁcation and regression. It is a tree structure with nodes and leaf nodes, where each node represents a test and each leaf node represents a predicted class or value.

Source document(s) used: scikit-learn-docs.pdf

Sources:
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf

================================================================================
QUESTION 8
================================================================================
Question:
What is a convolutional neural network?

Answer:
A convolutional neural network (CNN) is a type of neural network that uses convolutional layers to process data. In the context of the provided documents, a CNN is described as a network that uses convolutional layers to take in an image, perform a weighted sum of the input pixels, and produce an output.

In the documents, it is mentioned that a CNN is used as a filter that takes one or more images as input and produces other images as output. The CNN is trained during training, based on the examples it has seen and on the desired outputs for those examples.

It is also mentioned that a CNN can be used for tasks such as image classification and object detection, and that it can be used to analyze multichannel 2D features.

Source documents used:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf (figure 2.3 and figure 11.5)
- Deep-Learning-with-PyTorch.pdf (figure 8.8)
- Deep-Learning-with-PyTorch.pdf (figure 11.6)

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 9
================================================================================
Question:
What is an embedding?

Answer:
An embedding is a numeric vector that represents a word or concept in a vocabulary. It is often used to efficiently represent categorical data, and is particularly useful when one-hot encoding becomes cumbersome.

Source document(s) used: Deep-Learning-with-PyTorch.pdf

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- scikit-learn-docs.pdf
- Deep-Learning-with-PyTorch.pdf

================================================================================
QUESTION 10
================================================================================
Question:
What is regularization?

Answer:
Regularization is a mathematical tool aimed at easing the optimization process in training a model, specifically to control overfitting by adding a penalty term to the loss function. This term is crafted to limit the growth of model weights, making the loss have a smoother topography and reducing the gain from fitting individual samples.

The most popular regularization terms are L2 regularization (the sum of squares of all weights) and L1 regularization (the sum of the absolute values of all weights), which are both scaled by a small factor, known as a hyperparameter.

The reason for this name is that, in SGD, the regularization term can "decay" the weights towards zero, hence the name "weight decay".

Source documents used:

1. Deep-Learning-with-PyTorch.pdf
2. scikit-learn-docs.pdf (specifically, the sections on Regularization and Elastic-Net regularization)

Sources:
- Deep-Learning-with-PyTorch.pdf
- Deep-Learning-with-PyTorch.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf
- scikit-learn-docs.pdf

In [32]:
import pandas as pd

evaluation_table = pd.DataFrame(evaluation_results)

evaluation_table

,question,sources,answer,correct,grounded
0,What is overfitting?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",Overfitting is a situation where a model start...,,
1,What is underfitting?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",The information was not found in the provided ...,,
2,What is a neural network?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...","According to the provided documents, a neural ...",,
3,What is a tensor?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...","According to the provided context, a tensor re...",,
4,What is gradient descent?,"[scikit-learn-docs.pdf, scikit-learn-docs.pdf,...",Gradient descent is an optimization algorithm ...,,
5,What is cross-validation?,"[scikit-learn-docs.pdf, scikit-learn-docs.pdf,...",Cross-validation is a procedure used in machin...,,
6,What is a decision tree?,"[scikit-learn-docs.pdf, scikit-learn-docs.pdf,...",A decision tree is a non-parametric supervised...,,
7,What is a convolutional neural network?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",A convolutional neural network (CNN) is a type...,,
8,What is an embedding?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",An embedding is a numeric vector that represen...,,
9,What is regularization?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",Regularization is a mathematical tool aimed at...,,

In [34]:
evaluation_table["correct"] = [
    "Yes",  # 1. Overfitting
    "No",   # 2. Underfitting
    "Yes",  # 3. Neural network
    "Yes",  # 4. Tensor
    "Yes",  # 5. Gradient descent
    "Yes",  # 6. Cross-validation
    "Yes",  # 7. Decision tree
    "Yes",  # 8. Convolutional neural network
    "Yes",  # 9. Embedding
    "Yes"   # 10. Regularization
]

evaluation_table["grounded"] = [
    "Yes",  # 1. Overfitting
    "No",   # 2. Underfitting
    "Yes",  # 3. Neural network
    "Yes",  # 4. Tensor
    "Yes",  # 5. Gradient descent
    "Yes",  # 6. Cross-validation
    "Yes",  # 7. Decision tree
    "Yes",  # 8. Convolutional neural network
    "Yes",  # 9. Embedding
    "Yes"   # 10. Regularization
]

evaluation_table

,question,sources,answer,correct,grounded
0,What is overfitting?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",Overfitting is a situation where a model start...,Yes,Yes
1,What is underfitting?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",The information was not found in the provided ...,No,No
2,What is a neural network?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...","According to the provided documents, a neural ...",Yes,Yes
3,What is a tensor?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...","According to the provided context, a tensor re...",Yes,Yes
4,What is gradient descent?,"[scikit-learn-docs.pdf, scikit-learn-docs.pdf,...",Gradient descent is an optimization algorithm ...,Yes,Yes
5,What is cross-validation?,"[scikit-learn-docs.pdf, scikit-learn-docs.pdf,...",Cross-validation is a procedure used in machin...,Yes,Yes
6,What is a decision tree?,"[scikit-learn-docs.pdf, scikit-learn-docs.pdf,...",A decision tree is a non-parametric supervised...,Yes,Yes
7,What is a convolutional neural network?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",A convolutional neural network (CNN) is a type...,Yes,Yes
8,What is an embedding?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",An embedding is a numeric vector that represen...,Yes,Yes
9,What is regularization?,"[Deep-Learning-with-PyTorch.pdf, Deep-Learning...",Regularization is a mathematical tool aimed at...,Yes,Yes

In [35]:
print("Total questions:", len(evaluation_table))

print(
    "Correct answers:",
    (evaluation_table["correct"] == "Yes").sum()
)

print(
    "Grounded answers:",
    (evaluation_table["grounded"] == "Yes").sum()
)

Total questions: 10
Correct answers: 9
Grounded answers: 9

In [36]:
failure_cases = []

for _, row in evaluation_table.iterrows():

    if row["correct"] != "Yes" or row["grounded"] != "Yes":

        failure_cases.append({
            "question": row["question"],
            "answer": row["answer"],
            "possible_mitigation": (
                "Improve chunking, retrieve more relevant chunks, "
                "or improve the RAG prompt."
            )
        })

print("Number of failure cases:", len(failure_cases))

for case in failure_cases:
    print("\nQuestion:", case["question"])
    print("Possible mitigation:", case["possible_mitigation"])

Number of failure cases: 1

Question: What is underfitting?
Possible mitigation: Improve chunking, retrieve more relevant chunks, or improve the RAG prompt.

In [38]:
print("Vector store path:")
print(vector_store_path)

print("\nCollection name:")
print(collection.name)

print("\nNumber of stored chunks:")
print(collection.count())

print("\nEmbedding model:")
print("all-MiniLM-L6-v2")

print("\nChunk size:")
print(1000)

print("\nChunk overlap:")
print(200)

print("\nRetrieval count:")
print(5)

Vector store path:
../data/vector_store

Collection name:
rag_documents

Number of stored chunks:
18530

Embedding model:
all-MiniLM-L6-v2

Chunk size:
1000

Chunk overlap:
200

Retrieval count:
5